spring:
  application:
    name: RESTfull_Athtorisation

  datasource:
    username: Kirill
    password: 191919
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users_db


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
